{% set name = "vpython" %}
{% set version = "7.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 46fd11affc1b996554d7c6d0567fbd845ee5ead559ab9fd4db963eabe6b3da3e

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
  run:
    - autobahn >=18.8.2
    - ipykernel
    - jupyter
    - jupyter-server-proxy
    - numpy
    - python

test:
  imports:
    - vpython

about:
  home: https://vpython.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "VPython: 3D visualization made easy"
  description: |
    VPython makes it is to create and manipulate objects in three
    dimensions. For example, create a sphere with `my_sphere = vp.sphere()`
    and update its position with `my_sphere.pos = vp.vector(1, 2, 3)`.
  doc_url: https://vpython.org/
  dev_url: https://github.com/vpython/vpython-jupyter

extra:
  recipe-maintainers:
    - mwcraig
