{% set name = "vpython" %}
{% set version = "7.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 732ec3a1a57a55efd2eb1b27e4f2eaa5fe061f081b215a820418eca811e51e40

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
  run:
    - autobahn >=18.8.2
    - ipykernel
    - jupyter
    - jupyter-server-proxy
    - numpy
    - python

test:
  imports:
    - vpython

about:
  home: https://vpython.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'VPython: 3D visualization made easy'
  description: |
    VPython makes it is to create and manipulate objects in three
    dimensions. For example, create a sphere with `my_sphere = vp.sphere()`
    and update its position with `my_sphere.pos = vp.vector(1, 2, 3)`.
  doc_url: https://vpython.org/
  dev_url: https://github.com/vpython/vpython-jupyter

extra:
  recipe-maintainers:
    - sspickle
    - mwcraig
