{% set name = "vpython" %}
{% set version = "7.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26d0fe4c4f253c36a570ade3924cee2423b2feb5e6082ff5d5f2eac093e746df

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]
  skip: true  # [py>310 and ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - setuptools_scm
  run:
    - autobahn >=22.6.1,<27
    - ipykernel
    - jupyterlab >=4,<5
    - jupyter-server-proxy
    - jupyterlab-vpython >=3.1.8
    - numpy
    - python

test:
  imports:
    - vpython

about:
  home: https://vpython.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'VPython: 3D visualization made easy'
  description: |
    VPython makes it is to create and manipulate objects in three
    dimensions. For example, create a sphere with `my_sphere = vp.sphere()`
    and update its position with `my_sphere.pos = vp.vector(1, 2, 3)`.
  doc_url: https://vpython.org/
  dev_url: https://github.com/vpython/vpython-jupyter

extra:
  recipe-maintainers:
    - sspickle
    - mwcraig
